### ISSUE TITLE
Extract error: unallowed token at this point in JSON text (Yajl::ParseError)

### ISSUE THREAD

**Issue by ariella1R** [Shopify/shopify_transporter#133]
Converting Orders 

#### Problem:
```
versions/2.5.1/lib/ruby/gems/2.5.0/gems/yajl-ruby-1.4.1/lib/yajl.rb:44:in `parse'
/Users/ariellacheskisgold/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/yajl-ruby-1.4.1/lib/yajl.rb:44:in `parse': parse error: unallowed token at this point in JSON text (Yajl::ParseError)
          rEntity"       }     }   },  ]
                     (right here) ------^

```

#### Steps to Reproduce:
List the steps we can take to reproduce the problem:

1.
2.

**Comment by surajreddy** [comment]
This is related to https://github.com/Shopify/shopify_transporter/issues/134 and I think it happened because the process was early exited, or the file was manually edited. 

For anyone else running into this, this error is caused if the order file being converted has any JSON validation issues. Checking the file for valid JSON format can reveal any issues. In this case, it was an extra `,` at the end of the list of JSON orders.
