### ISSUE TITLE
Extract from Magento returns empty JSON file

### ISSUE THREAD

**Issue by jamesco** [Shopify/shopify_transporter#140]
#### Problem:
Running the transporter returns an empty JSON file that only consists of square brackets:
`[ ]`

No error messages are given. This happens when trying to extract Customers, Products, or Orders. I've tried changing the limits to 1000, 100, and 10 and it's the same result every time. Is there anywhere I can look for in-depth debug/log info?

#### Steps to Reproduce:
List the steps we can take to reproduce the problem:

1. Get config.yml info for client's site
2. Attempt to run Transporter.

**Comment by mimperatore** [comment]
It's hard to say what the issue is with the information provided.

Can you share your config (obviously, do not share API/DB credentials)?  Did you make any customizations, and if so, what are they?  Can you share the command you're running?

This gem's source code is completely available to you.  Feel free to step through to try to identify the root cause of the issue, and please submit a PR if you think it's something that would be beneficial to others.

**Comment by jamesco** [comment]
Closing this issue, after 5 days of help with a Shopify Plus Launch Engineer (and countless back and forth tickets with Rackspace) we were able to solve it.
