### ISSUE TITLE
When extracting orders i am getting Savon::HTTPError.

### ISSUE THREAD

**Issue by gopalvirat** [Shopify/shopify_transporter#35]
#### Problem:
When extracting orders i am getting this error.
`'raise_soap_and_http_errors!': HTTP error (500) (Savon::HTTPError)`

#### Steps to Reproduce:

1.Checkout the `master` branch
2.Run `./shopify_transporter export --config=../config.yml --object=order > orders.json`
3 See below error
![orders_export_error](https://user-images.githubusercontent.com/35100967/45618582-dcabb700-ba93-11e8-8767-454f3fefe892.png)

**Comment by gopalvirat** [comment]
@daveshawsa thanks for the quick response.

I already don't include 'www'.

**Comment by gopalvirat** [comment]
The above command is working fine for less number of records, for instance for 15000 orders it is working fine but above that, it is producing the above error [https://github.com/Shopify/shopify_transporter/issues/35#issue-360810082](url).

I think there is a memory issue here as well, as in case of #15 but not sure why it is not throwing a memory related exception.

**Comment by surajreddy** [comment]
@gopalvirat for both of these issues I would suggest trying some of the code in the https://github.com/Shopify/shopify_transporter/tree/extraction-scripts-by-daterange branch. There is a readme for this at https://github.com/Shopify/shopify_transporter/blob/extraction-scripts-by-daterange/sample_scripts/third_party_platform_exporting/magento/v1.9/soap_api/README.md

This will be merged with the primary tool soon, but it needs some more work before it can be fully integrated.

I'm suspecting that because there are a lot of customers, the server is not able to handle the SOAP request.

Feel free to comment here if you are running into issues with the other branch.

**Comment by chrismarkpd** [comment]
@surajreddy when trying to export magento customers using the customers.rb script, I get the following error:

`response.rb:90:in `raise_invalid_response_error!': Unable to parse response body: (Savon::InvalidResponseError)`

Exporting orders worked fine. Thanks for these features! I'm using the extraction-scripts-by-daterange branch.

**Comment by surajreddy** [comment]
@chrismarkpd I'm glad the orders export worked!

Do you mind opening a new issue for the problem with the `customers.rb` script? Are there more lines printed in the error? If so, can you share those in that issue as well?

**Comment by chrismarkpd** [comment]
@surajreddy opened up a new issue and shared more lines. Thanks!

**Comment by surajreddy** [comment]
@gopalvirat the newest version of the gem now supports extracting data: https://github.com/Shopify/shopify_transporter/releases

We've added support for retrieving data in batches in the newest version of the gem, and that should get past this error. Please re-open this issue if you are running into the error again.
